spring.application.name=demo
# 数据库连接地址，mem:bookstore 表示存在内存里，数据库名叫 bookstore
spring.datasource.url=jdbc:h2:mem:bookstore
# H2 Console 开关，默认是关的，打开它
spring.h2.console.enabled=true
# 关掉 Hibernate 的自动建表
spring.jpa.hibernate.ddl-auto=none
# 告诉 Spring Boot changelog 文件在哪
#spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml
#debug=true